[build]
command = "npm run data && npm run generate"
publish = "./dist"

[build.environment]
NODE_ENV = "production"
NPM_CONFIG_AUDIT = "false"
NPM_CONFIG_FUND = "false"

[build.processing.html]
pretty_urls = true

[[headers]]
for = "/*"
[headers.values]
Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"
Referrer-Policy = "no-referrer-when-downgrade"
X-Content-Type-Options = "nosniff"
X-Frame-Options = "SAMEORIGIN"
X-XSS-Protection = "1; mode=block"

[[headers]]
for = "/_nuxt/*"
[headers.values]
Cache-Control = "public, max-age=31536000, immutable"
