SET default_tablespace = '';

SET default_table_access_method = "heap";

CREATE TABLE "public"."access_points_latest_states" (
    "updated_at" timestamp with time zone NOT NULL,
    "building_number" bigint,
    "room_id" "text",
    "device_count" bigint NOT NULL,
    "floor" "text" NOT NULL,
    "access_point_name" "text" NOT NULL,
    "map_location" "text",
    "location_hierarchy" "text"
);

ALTER TABLE "public"."access_points_latest_states" OWNER TO "postgres";

CREATE TABLE "public"."buildings_latest_states" (
    "building_number" bigint NOT NULL,
    "updated_at" timestamp with time zone NOT NULL,
    "device_count" bigint NOT NULL
);

ALTER TABLE "public"."buildings_latest_states" OWNER TO "postgres";

CREATE TABLE "public"."busy" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"(),
    "status" "text"
);

ALTER TABLE "public"."busy" OWNER TO "postgres";

ALTER TABLE "public"."busy" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."busy_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE "public"."spaces_latest_states" (
    "building_number" bigint NOT NULL,
    "updated_at" timestamp with time zone NOT NULL,
    "room_id" "text" NOT NULL,
    "device_count" bigint NOT NULL
);

ALTER TABLE "public"."spaces_latest_states" OWNER TO "postgres";

ALTER TABLE ONLY "public"."buildings_latest_states"
    ADD CONSTRAINT "BuildingsCurrent_pkey" PRIMARY KEY ("building_number");

ALTER TABLE ONLY "public"."spaces_latest_states"
    ADD CONSTRAINT "SpacesCurrent_pkey" PRIMARY KEY ("building_number", "room_id");

ALTER TABLE ONLY "public"."access_points_latest_states"
    ADD CONSTRAINT "access_points_latest_states_pkey" PRIMARY KEY ("access_point_name");

ALTER TABLE ONLY "public"."busy"
    ADD CONSTRAINT "busy_pkey" PRIMARY KEY ("id");

CREATE POLICY "Enable read access for all users" ON "public"."buildings_latest_states" FOR SELECT USING (true);

CREATE POLICY "Enable read access for all users" ON "public"."busy" FOR SELECT USING (true);

CREATE POLICY "Enable read access for all users" ON "public"."spaces_latest_states" FOR SELECT USING (true);

ALTER TABLE "public"."buildings_latest_states" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."busy" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."spaces_latest_states" ENABLE ROW LEVEL SECURITY;

GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";

GRANT ALL ON TABLE "public"."access_points_latest_states" TO "anon";
GRANT ALL ON TABLE "public"."access_points_latest_states" TO "authenticated";
GRANT ALL ON TABLE "public"."access_points_latest_states" TO "service_role";

GRANT ALL ON TABLE "public"."buildings_latest_states" TO "anon";
GRANT ALL ON TABLE "public"."buildings_latest_states" TO "authenticated";
GRANT ALL ON TABLE "public"."buildings_latest_states" TO "service_role";

GRANT ALL ON TABLE "public"."busy" TO "anon";
GRANT ALL ON TABLE "public"."busy" TO "authenticated";
GRANT ALL ON TABLE "public"."busy" TO "service_role";

GRANT ALL ON SEQUENCE "public"."busy_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."busy_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."busy_id_seq" TO "service_role";

GRANT ALL ON TABLE "public"."spaces_latest_states" TO "anon";
GRANT ALL ON TABLE "public"."spaces_latest_states" TO "authenticated";
GRANT ALL ON TABLE "public"."spaces_latest_states" TO "service_role";
