name: Audit Netlify Deploy Preview
on:
  check_suite:
    types: [completed]

jobs:
  integration:
    name: Run integration tests
    runs-on: ubuntu-latest
    steps:

      - name: Git checkout
        if: github.event.check_suite.app.name == 'Netlify' && github.event.check_suite.conclusion == 'success'
        uses: actions/checkout@master

      - name: Install Node
        if: github.event.check_suite.app.name == 'Netlify' && github.event.check_suite.conclusion == 'success'
        uses: actions/setup-node@v1
        with:
          node-version: 10.x

      - name: Install npm dependencies
        if: github.event.check_suite.app.name == 'Netlify' && github.event.check_suite.conclusion == 'success'
        run: npm install --no-optional --no-audit

      - uses: ./.github/actions/get-netlify-url
        if: github.event.check_suite.app.name == 'Netlify' && github.event.check_suite.conclusion == 'success'
        id: get-netlify-url

      - name: Run Cypress
        if: github.event.check_suite.app.name == 'Netlify' && github.event.check_suite.conclusion == 'success'
        uses: ./.github/actions/run-cypress
        with:
          base-url: ${{ steps.get-netlify-url.outputs.url }}
