name: Node.js CI

on: pull_request

jobs:
  ci:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    env:
      USE_MOCK_DATA_CMS: 1
      CSV_PATH: ./data/studieplekken-latest.csv
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"

      - name: Use dependencies cache
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('package-lock.json') }}
          restore-keys: npm-

      - name: Install dependencies
        run: npm ci --ignore-scripts --no-audit --no-fund

      - name: Run unit tests
        run: npm run test:unit

      - name: Lint code
        run: npm run lint -- --max-warnings 0
