name: Node CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@v1
      with:
        node-version: '10.x'

    - name: install npm dependencies
      run: npm install --no-optional
      env:
        CI: true

    - name: run unit tests
      run: npm test

    - name: lint files
      run: npm run lint -- --max-warnings 0
